server:
  port: 8761
# config data bases
spring:
  # config Rabbitmq
  cloud:
    stream:
      #bindings:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq.train.air.c.transoft.bo #192.168.110.110
                port: 5672
                username: admin
                password: admin
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
