# config data bases
spring:
  # config rabbitmq
  cloud:
    stream:
      bindings:
        pnrCreatedReserveChannel:
          binder: rabbit1
          destination: pnr.created.reserve
          group: pnrcreatedreservegroup
        pnrCanceledReserveChannel:
          binder: rabbit1
          destination: pnr.canceled.reserve
          group: pnrcanceledreservegroup
        fareClassCreatedChannel:
          binder: rabbit1
          destination: fareclass.created
          group: fareclasscreatedgroup
        segmentCreatedChannel:
          binder: rabbit1
          destination: segment.created
          content-type: application/json
          group: segmentcreatedgroup
        pnrActiveFCChannel:
          binder: rabbit1
          destination: pnrFC.active
          content-type: application/json
          group: pnrFCactivegroup
        pnrCanceledActiveFCChannel:
          binder: rabbit1
          destination: pnrCancelFC.active
          content-type: application/json
          group: pnrCancelFCactivegroup
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq.train.air.c.transoft.bo #config ip rabbitmq  192.168.110.110
                port: 5672
                username: admin
                password: admin
  #profiles: test
  #jmx:
    #enabled: false
# Datasource and JPA configuration to be used for using the same tokenstore as the authorization server for
# the defined resource server. Note that there can't be 2 different root nodes, so datasource falls under the "spring" node.
  datasource:
    url: jdbc:mysql://db.train.air.c.transoft.bo:3306/flight_control?useSSL=false  #192.168.110.110
    username: airdbuser
    password: Transoft1!
    driver-class: com.mysql.jdbc.Driver
    #initialize: true
    #separator: ^
    #continueOnError: false
    #schema: classpath:/db-scripts/0.0.1/schema.sql
    #data: classpath:/db-scripts/0.0.1/masterData.sql
#
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      #ddl-auto: create
      show_sql: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: 
    com.transoft.completeair.flightcontrol: DEBUG

  # Logger-specific levels.
  loggers:

    # Redirects SQL logs to a separate file
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG

# Note: import disable mode product and active mode Dev
server:
  port: 8081
# config 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.train.air.c.transoft.bo:8761/eureka/  #192.168.110.110
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

security:
  oauth2:
    resource:
      userInfoUri: http://oauth.train.air.c.transoft.bo:9999/uaa/api/user  #192.168.110.111

