# config data bases
spring:
  # config Rabbitmq
  cloud:
    stream:
      bindings:
        pnrCreatedReserveChannel:
          binder: rabbit1
          destination: pnr.created.reserve
          content-type: application/json
          group: pnrcreatedreservegroup
        pnrCanceledReserveChannel:
          binder: rabbit1
          destination: pnr.canceled.reserve
          content-type: application/json
          group: pnrcanceledreservegroup
        pnrCanceledFinanceChannel:
          binder: rabbit1
          destination: pnr.canceled.finance
          content-type: application/json
          group: pnrcanceledfinancegroup
        pnrActiveFCChannel:
          binder: rabbit1
          destination: pnrFC.active
          group: pnrFCactivegroup
        pnrActiveFinanceChannel:
          binder: rabbit1
          destination: pnrF.active
          group: pnrFactivegroup
        pnrInvoiceSoldChannel:
          binder: rabbit1
          destination: pnr.invoice.sold
          content-type: application/json
          group: pnrinvoicesoldgroup
        pnrCanceledActiveFCChannel:
          binder: rabbit1
          destination: pnrCancelFC.active
          group: pnrCancelFCactivegroup
        pnrActiveFinanceCancelChannel:
          binder: rabbit1
          destination: pnrF.active.cancel
          group: pnrFactivecancelgroup
        pnrInvoiceLuggageChannel:
          binder: rabbit1
          destination: pnr.created.luggage
          content-type: application/json
          group: pnrcreatedluggagegroup
        pnrActiveFLuggageChannel:
          binder: rabbit1
          destination: pnrActiveF.luggage
          group: pnrActiveFLuggagegroup
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq.train.air.c.transoft.bo #config ip rabbitmq 192.168.110.110
                port: 5672
                username: admin
                password: admin
  #profiles: test
  #jmx:
    #enabled: false
# Datasource and JPA configuration to be used for using the same tokenstore as the authorization server for
# the defined resource server. Note that there can't be 2 different root nodes, so datasource falls under the "spring" node.
  datasource:
    url: jdbc:mysql://db.train.air.c.transoft.bo:3306/pnr  #192.168.110.116
    username: airdbuser
    password: Transoft1!
    driver-class: com.mysql.jdbc.Driver
    #initialize: true
    #separator: ^
    #continueOnError: false
    #schema: classpath:/db-scripts/0.0.1/schema.sql
    #data: classpath:/db-scripts/0.0.1/masterData.sql
#
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      #ddl-auto: create
      show_sql: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level:
    com.transoft.completeair.pnr: DEBUG

  # Logger-specific levels.
  loggers:

    # Redirects SQL logs to a separate file
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
# config Oauth
serviceOauth:
  login: http://oauth-service/uaa/oauth/token?client_id=
  refresh: http://oauth-service/uaa/oauth/token?grant_type=refresh_token&refresh_token=
  logout: http://oauth-service/uaa/api/logout-up
  account: http://oauth.train.air.c.transoft.bo:9999/uaa/api/account  #192.168.110.111
# Note: import disable mode product and active mode Dev
server:
  port: 8087
# config eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.train.air.c.transoft.bo:8761/eureka/  #192.168.110.111
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

security:
  oauth2:
    resource:
      userInfoUri: http://oauth.train.air.c.transoft.bo:9999/uaa/api/user #192.168.110.111
